---
- hosts: all
  become: yes
  tasks:
  - name: Chenking ping
    ping:
  - name: Update packages
    apt:
      name: apache2
      update_cache: yes
      state: present
  - name: restart apache2 server
    service:
      name: apache2
      enable: yes
      state: restarted
  - name: install php module
    apt:
      name: "{{ item }}"
      state: present
    with_items:
     - php
     - libapache2-mod-php5
     - php-mcrypt
     - php-mysql
  - name: restart apache2 afetr restart
    service:
      name: apache2
      enabled: yes
      state: restarted
